<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TasksApi.Tests/**" />
    <Content Remove="TasksApi.Tests/**" />
    <None Remove="TasksApi.Tests/**" />
    <EmbeddedResource Remove="TasksApi.Tests/**" />
  </ItemGroup>

</Project>
